from typing import Final

PROTOCOL_VERSION: Final = 1
MAX_INGEST_MESSAGE_BYTES: Final = 64 * 1024
MAX_CAPTION_TEXT_LENGTH: Final = 20_000
MAX_SPEAKER_LENGTH: Final = 512
MAX_EXTENSION_BUFFER_EVENTS: Final = 2_000
MAX_EXTENSION_BUFFER_BYTES: Final = 4 * 1024 * 1024
HEARTBEAT_INTERVAL_SECONDS: Final = 20
STOP_FINALIZE_GRACE_SECONDS: Final = 2
RECONNECT_MAX_DELAY_SECONDS: Final = 30
MAX_AGENT_OUTPUT_CHARACTERS: Final = 1_000_000
MAX_QUEUED_AGENT_RUNS_PER_SESSION: Final = 100
MAX_INGEST_EVENTS_PER_SECOND: Final = 200
UI_SEND_TIMEOUT_SECONDS: Final = 5
